#!/usr/bin/env bash

# Create a backup snapshot imaage of Digital Ocean droplet

usage() {
	>&2 echo "Usage: $0 DROPLET_NAME IMAGE_NAME"
	exit 1
}
argc=$#
(( argc != 2 )) && usage

droplet_name=$1 ; shift
image_name=$1 ; shift

droplet_id=$(`dirname $0`/droplet-id $droplet_name)
test "$droplet_id" = "" && >&2 echo "Droplet not found." && exit 1

doctl compute droplet-action snapshot $droplet_id --snapshot-name $image_name

