#!/usr/bin/env bash

# Disallow Wordpress app to write to entire site directory except for wp-content

[[ $(id -u) != 0 ]] && >&2 echo "Error: Must be sudo/root." && exit 1

html_dir="$1"
[[ $html_dir == "" ]] && >&2 echo "Error: Directory required." && exit 1


## Set permissions for wordpress to write to entire site directory
echo "Update security context of all site files to disallow wordpress app to write to entire directory."
ls -l -Z $html_dir

if command -v getenforce && [[ $(getenforce) = Enforcing ]]; then
	#sudo chcon -R unconfined_u:object_r:user_home_t:s0 $html_dir

	#sudo chcon -R -t user_home_t $html_dir
	sudo chcon -t user_home_t $html_dir

	sudo restorecon -vR $html_dir
fi

sudo chmod g-w -R $html_dir

# Keep allowing wordpress to write to wp-content
echo "Allow wordpress to write to wp-content"
#sudo chcon -R -t httpd_sys_rw_content_t "$html_dir/wp-content"
sudo chmod g+w -R "$html_dir/wp-content"

#sudo chown -R $SUDO_USER $html_dir

echo "Updated context:"
ls -l -Z $html_dir

