#!/usr/bin/env bash

# Sets up a basic secure web server
## Includes: firewall, secure SSH settings, sudo user, updates, cronjobs


# Args

while [[ $# -gt 0 ]]; do
	case "$1" in
		-h|--host) host="$2"; shift; shift;;
		-u) user="$2"; shift; shift;;
		-i) ssh_key="$2"; shift; shift;;
		-k|--authorized_keys) authorized_keys="$2"; shift; shift;;
		-p|--port) port="$2"; shift; shift;;
		-n|--new_user) new_user="$2"; shift; shift;;
		--update) should_update=y; shift;;
		--local) run_local=y; shift;;
		-*|*) echo "Unknown option: $1" >&2; exit 1;;
	esac
done

if [[ "" = "$host" && "" = "$run_local" ]]; then
	>&2 echo "Error: Argument for host required (or use --local for local execution)."
	exit 1
fi

[[ "" != "$port" ]] || port=22
[[ "" != "$user" ]] || user=root

if [[ "" != "$authorized_keys" ]]; then
	if ! grep -q "^ssh-rsa " <<< "$authorized_keys"; then
		>&2 echo "Error: value for authorized keys argument is invalid."
		>&2 echo "Received value of:"
		>&2 echo '```'
		>&2 echo "$authorized_keys"
		>&2 echo '```'
		>&2 echo "Please check how keys are being passed and try again."
		exit 1
	fi
fi


# Main

## Construct command to be run on a bash-compatible shell

command="
echo \"INFO [\$(date)]: Begin server setup.\"
"

### Command arguments
command+="
# Arguments
user='$user'
authorized_keys='$authorized_keys'
new_user='$new_user'
"


### Transfer utility scripts for system administration
#### WARNING: If a script contains single quotes, please ensure that it does not also contain the delimeter we chose to use in sed, namely '%'. If there is a conflict, investigate for another delimiter.

sbin_script_files=(
	tmst		# Return current timestamp (UTC) in a filename-friendly form
	bak 		# Backup file while including date created
	add-sudoer	# Quickly add password-less sudo users
	reboot.sh	# Reboot system after writing log
	on-poweron	# Cronjob script to execute upon system poweron (includes logging)
	os-name		# Return OS name of current system
	chdirgroup	# Recursively update group owner of directory
	randpw		# Generate a random password
	cp-app-files	# Copy app files to remote server
	remove-swap	# Remove swap space from system
	private-ip	# Return private IP address of system (if it exists)
	firewall-add-rule	# Allow connection to port from IP address
	firewall-remove-rule	# Remove rule for connection to port from IP address
	execute-immediate-cronjob	# Execute next queued cronjob immediately
	scan-logs-for-errors 	# Scan directory files for lines indicating an error
	file-exists		# Return true if file exists, using the find command
)
for file in "${sbin_script_files[@]}"; do
	contains_single_quotes=n
	if grep -q "'" ./sbin/$file; then
		contains_single_quotes=y
		#### Hack to ensure that single quote (') characters can be transferred successfully
		script=$(sed "s%'%SINGLE_QUOTE%g" < "./sbin/$file")
	else
		script=$(<"./sbin/$file")
	fi
	command+="
		sudo tee /usr/local/sbin/$file <<< '$script' >/dev/null
		sudo chmod +x /usr/local/sbin/$file
		if test -f /etc/centos-release; then
			sudo ln -s /usr/local/sbin/$file /usr/sbin
		fi
		"
	if [[ $contains_single_quotes = y ]]; then
		command+="
			sudo sed -i \"s%SINGLE_QUOTE%'%g\" /usr/local/sbin/$file
			"
	fi
done


### Add on-poweron script as entry to system crontab
command+="
file=/usr/local/sbin/on-poweron
if ! grep -q \"\$file\" /etc/crontab; then
	sudo bak /etc/crontab
	echo 'INFO: Add on-poweron script to crontab...'
	echo \"@reboot		root	\$file\" | sudo tee -a /etc/crontab >/dev/null
fi
"

### Create directory to log system power cycles
command+="
sudo mkdir -v /var/log/power-state
"

### Ensure that logs for systemd-journald (journalctl) persists across system reboots
### # Reference: `man systemd-journald.service`
command+="
if [[ ! -d /var/log/journal ]]; then
	echo 'INFO: Enabling persistent journal logs.'
    sudo mkdir -vp /var/log/journal
    echo 'INFO: Setting correct permissions on /var/log/journal...'
    sudo systemd-tmpfiles --create --prefix /var/log/journal
    sudo systemctl restart systemd-journald
fi
"

### Create directories to hold scripts and logs for initial setup
command+="
sudo mkdir -vp /usr/local/setup /var/log/setup
"

### Transfer script that will secure server, to execute immediately
command+="
echo '$(<./setup/secure-server)' | sudo tee /usr/local/setup/secure-server >/dev/null
"

### Transfer script of updates for server to self-execute later
command+="
echo '$(<./setup/update-server)' | sudo tee /usr/local/setup/update-server >/dev/null
"

### Log information about arguments provided to script
command+="
if [[ '' != \"\$authorized_keys\" ]]; then
	echo 'INFO: SSH public keys provided to be transferred.' \
		| sudo tee /var/log/setup/secure-server
	echo 'INFO: SSH password authentication will be disabled.' \
		| sudo tee /var/log/setup/secure-server
else
	echo 'INFO: No SSH keys provided.' \
		| sudo tee /var/log/setup/secure-server
fi
if [[ '' != \"\$new_user\" ]]; then
	echo 'INFO: New user \"$new_user\" will be created.' \
		| sudo tee /var/log/setup/secure-server
fi
if [[ 'root' != \"\$user\" || '' != \"\$new_user\" ]]; then
	echo 'INFO: Root user SSH login will be disabled.' \
		| sudo tee /var/log/setup/secure-server
fi
"

### If adding a new user without authorized keys, copy from root's authorized keys
command+="
if [[ '' != \"\$new_user\" && '' = \"\$authorized_keys\" ]]; then
	echo 'INFO: No authorized keys provided for new user; copying from root.'
	if [[ -f /root/.ssh/authorized_keys && -s /root/.ssh/authorized_keys ]]; then
		authorized_keys=\"\$(cat /root/.ssh/authorized_keys)\"
	else
		echo 'ERROR: Root has no authorized keys. Cannot create new user without SSH keys.' >&2
		exit 1
	fi
fi
"

### Commence server-side script execution
command+="
sudo bash /usr/local/setup/secure-server \
	-k \"\$authorized_keys\" \
	-u \"\$user\" \
	-n \"\$new_user\" \
	2>&1 | sudo tee /var/log/setup/secure-server
"

### Enqueue update script if requested via option
if [[ $should_update != "" ]]; then
	command+="
	# Add cronjob so that server will execute next setup script on its own
	echo 'INFO: Set cronjob so that the update script will run at the next minute.'
	echo '* *	* * *	root	bash /usr/local/setup/update-server \
		>> /var/log/setup/update-server 2>&1 \
		# initial setup script ; remove_immediately \
		' | sudo tee -a /etc/crontab >/dev/null
	"
fi

### End command
command+="
echo \"INFO [\$(date)]: Server setup complete.\"
"

## Execute command on target server (or locally)

if [[ "$run_local" = "y" ]]; then
	bash -c "$command"
elif [[ "" != "$ssh_key" ]]; then
	ssh -i "$ssh_key" -p "$port" "$user@$host" "$command"
else
	ssh -p "$port" "$user@$host" "$command"
fi

