#!/usr/bin/env bash

# Install node
# Reference for nodesource: https://github.com/nodesource/distributions

[[ $(id -u) != 0 ]] && echo "Error: Must be run as sudo/root." && exit 1


node_version=12


if [[ $(command -v dnf) != "" ]]; then
	# Update system to source Node-related packages from nodesource.com
	curl -sL https://rpm.nodesource.com/setup_$node_version.x | sudo bash -

	# Install Node binary
	sudo dnf install -y nodejs

	# Install build tools to compile and install native addons from npm
	sudo dnf install -y gcc-c++ make

	# Install Yarn package manager
	curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
	sudo dnf install -y yarn

elif [[ $(command -v apt) != "" ]]; then
	# Update system to source Node-related packages from nodesource.com
	curl -sL https://deb.nodesource.com/setup_$node_version.x | sudo -E bash -

	# Install Node binary
	sudo apt-get install -y nodejs

	# Install build tools to compile and install native addons from npm
	sudo apt-get install -y build-essential

	# Install Yarn package manager
	curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
	echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
	sudo apt-get update && sudo apt-get install -y yarn
	sudo apt-get install -y yarn

fi
