#!/usr/bin/env bash

# Install node
# Reference for nodesource: https://github.com/nodesource/distributions

[[ $(id -u) != 0 ]] && echo "Error: Must be run as sudo/root." && exit 1


node_version=lts


if [[ $(command -v dnf) != "" ]]; then
	# Update system to source Node-related packages from nodesource.com
	curl -fsSL https://rpm.nodesource.com/setup_$node_version.x | sudo bash -

	# Install Node binary
	sudo dnf install -y nodejs

	# Install build tools to compile and install native addons from npm
	sudo dnf install -y gcc-c++ make

elif [[ $(command -v apt) != "" ]]; then
	# Update system to source Node-related packages from nodesource.com
	if [ -f "/etc/debian_version" ]; then
		curl -fsSL https://deb.nodesource.com/setup_$node_version.x | bash -
		apt-get install -y nodejs
		# Install build tools to compile and install native addons from npm
		apt-get install -y build-essential
	else
		curl -fsSL https://deb.nodesource.com/setup_$node_version.x | sudo -E bash -
		sudo apt-get install -y nodejs
		# Install build tools to compile and install native addons from npm
		sudo apt-get install -y build-essential
	fi

fi
