#!/usr/bin/env bash

# Install program, from script in setup/install, on remote server

[[ $# < 2 || $# > 3 ]] && >&2 echo "Usage: $0 PROGRAM_NAME DEST [NOW]" && exit 1


program_name="$1" ; shift
dest="$1" ; shift
now="$1" ; shift

dest_user=$(sed -E "s/(.*)@.*/\1/" <<< $dest)


## Copy script directory to remote server
echo "Uploading project files..."
$(dirname $0)/../sbin/cp-app-files . $dest:/opt/orc


## Create command to execute via SSH

script_path="setup/install/$program_name"
log="/var/log/$script_path"

command="
	# Ensure log directory exists
	[[ ! -d /var/log/setup/install ]] && sudo mkdir -vp /var/log/setup/install
	"

if [[ $now = "" ]]; then
	command+="
		echo \"INFO [\$(date)]: Set cronjob so the setup script will run at the next minute.\"
		sudo bak /etc/crontab >/dev/null
		echo \"\
			* *	* * *	$dest_user	\
			sudo sed -i \\\"\\|$script_path|d\\\" /etc/crontab \
			&& echo \"Executing cronjob that was scheduled at: \$(date)\" \
			&& echo \"__START__: \$\(date\)\" | sudo tee -a $log >/dev/null \
			&& sudo /opt/orc/$script_path 2>&1 | sudo tee -a $log >/dev/null \
			&& echo \"__END__: \$\(date\)\" | sudo tee -a $log >/dev/null \
			# IMMEDIATE_EXECUTE_AND_REMOVE \
			\" | sudo tee -a /etc/crontab >/dev/null
		"
else
	command+="
		echo \"INFO [\$(date)]: Executing /opt/orc/$script_path ...\" \
		echo \"Executing script that was scheduled at: \$(date)\" \
		&& echo \"__START__: \$(date)\" | sudo tee -a $log \
		&& sudo /opt/orc/$script_path 2>&1 | sudo tee -a $log \
		&& echo \"__END__: \$(date)\" | sudo tee -a $log
		"
fi


ssh $dest "$command"


# Note: To remove cronjob specifying $script_path:
#if grep -q "$script_path" /etc/crontab; then
#    bak /etc/crontab
#    sudo sed -i "\|$script_path|d" /etc/crontab
#fi

