#!/usr/bin/env bash

# Remove rule from firewall that allowed connections to a port from an IPv4 address

[[ $(id -u) != 0 ]] && >&2 echo "Error: Must be run as sudo/root." && exit 1

[[ $# != 2 ]] && >&2 echo "Usage: $0 PORT IP_ADDRESS" && exit 1

port=$1 ; shift
ip_address=$1 ; shift


## Set firewall rule to disallow connections to $port from $ip_address

firewalld_remove_rule() {
	zone=$(firewall-cmd --get-default-zone)
	backup_conf=$(sudo bak /etc/firewalld/zones/$zone.xml | sed -E "s/.* -> '(.*)'/\1/")
	sudo firewall-cmd --permanent --zone=$zone --remove-rich-rule="
		rule family=ipv4
		source address=$ip_address
		port protocol=tcp port=$port accept" >/dev/null
	if [[ $(diff /etc/firewalld/zones/$zone.xml $backup_conf) = "" ]]; then
		rm $backup_conf
		exit 1
	fi
	sudo firewall-cmd --reload
}
strip_cidr_suffix() { cut -f1 -d/ <<< "$1"; }
ufw_remove_rule() {
	local ip_address=$(strip_cidr_suffix $ip_address)
	rule_number=$(sudo ufw status numbered \
		| grep "] $port/tcp\s" | grep "\s$ip_address" | cut -f 2 -d" " | tr -d ])
	if [[ $rule_number = "" ]]; then
		exit 1
	fi
	sudo ufw --force delete $rule_number
}


main() {
	if command -v firewall-cmd >/dev/null; then
		firewalld_remove_rule
	elif command -v ufw >/dev/null; then
		ufw_remove_rule
	else
		>&2 echo "No recognized firewall installed."
		exit 1
	fi
}

main
