#!/usr/bin/env bash

# Return OS name (case-insensitive) of current system


is_centos() {
	[[ $(uname -s) = "Linux" && -f /etc/centos-release ]]
}

is_ubuntu() {
	[[ $(head -1 /etc/os-release) = 'NAME="Ubuntu"' ]]
}

is_mac() {
	[ $(uname -s) = "Darwin" ]
}

is_wsl() {
	[[ $(uname -s) = "Linux" && $(uname -a) =~ "Microsoft" ]]
}

if is_centos; then
	echo centos
elif is_ubuntu; then
	echo ubuntu
elif is_mac; then
	echo mac
elif is_wsl; then
	echo wsl
fi
