#!/usr/bin/env bash

# Create PostgreSQL database and user with basic privileges

[[ $(id -u) != 0 ]] && >&2 echo "Error: Must be run as sudo/root." && exit 1

[[ $# < 2 || $# > 4 ]] && >&2 echo "Usage: $0 DBNAME PASSWORD [CLIENT_HOST]" && exit 1

pgsql_version=$(sudo -u postgres \
	psql -c "\echo :VERSION" | cut -f 2 -d" " | cut -f1 -d.)


dbname=$1 ; shift
password=$1 ; shift
host=$1 ; shift

username=$dbname


## Create database
sudo -i -u postgres psql -c "
	CREATE DATABASE $dbname;
	" || exit 1


## Create user on database server
sudo -i -u postgres psql -c "
	CREATE USER $username PASSWORD '$password';
	" || exit 1
### If password contains special char, then set password via file instead of string.
###* Note: The '$' in the value for PASSWORD in CLI command string fails.
if [[ $password =~ \$ ]]; then
	echo "ALTER USER $username PASSWORD '$password'" > .tmp_alter_password.psql
	sudo -i -u postgres psql < .tmp_alter_password.psql
	rm .tmp_alter_password
fi


## Update authentication configuration with new rule

### Insert sert new authentication rule for user to access database
auth_conf=$(sudo -u postgres psql -t -P format=unaligned -c "SHOW hba_file")
echo "Update PostgreSQL host auth configuration file '$auth_conf'"

rule="local	$dbname	$username			scram-sha-256"
echo "- Inserting rule: '$rule'"
sudo sed -i -E "s/(^local\s+all\s+all\s+peer$)/$rule\n\1/" $auth_conf

if [[ $host != "" && $host != localhost ]]; then
	rule="host	$dbname	$username	$host\/32	scram-sha-256"
	echo "- Inserting rule: '$rule'"
	sudo sed -i -E "s/(^host\s+all\s+all\s+127\.0\.0\.1\/32\s+ident$)/$rule\n\1/" $auth_conf
fi

### Reload config settings
echo "Reload PostgreSQL server conf via: 'SELECT pg_reload_conf();'"
sudo -i -u postgres psql -c "SELECT pg_reload_conf();" >/dev/null

