#!/usr/bin/env bash

# Remotely set up Django web app, connecting to local SQLite database

usage() {
	>&2 echo "Usage: $0 WEBSITE_NAME APP_DEST"
	exit 1
}
argc=$#
(( argc < 2 || argc > 2 )) && usage

website_name="$1" ; shift
app_dest="$1" ; shift

sbin=$(dirname $0)/../sbin

[[ $website_name =~ @ ]] \
	&& >&2 echo "Invalid website name." && usage
! $sbin/is-valid-connection-value $app_dest \
	&& >&2 echo "Invalid connection value for app server." && usage


## Run setup script on remote server
echo "INFO [$(date)]: Executing script to set up Django web app on server... 🚀"
$(dirname $0)/setup-web django $website_name $app_dest --now

