#!/usr/bin/env bash

# Load Lets Encrypt directory (account key and certificates) onto remote server

[[ $# != 2 ]] && >&2 echo "Usage: $0 DEST ARCHIVE" && exit 1

dest="$1" ; shift
archive="$1" ; shift


echo "Transfer LetsEncrypt directory..."
scp -p $archive $dest:letsencrypt.tgz && \
ssh $dest "
	if ! command -v tar >/dev/null; then
		[[ ! -d /var/log/setup/install ]] && sudo mkdir -vp /var/log/setup/install
		printf \"INFO: Installing tar...\"
		sudo dnf install -y tar | sudo tee /var/log/setup/install/tar >/dev/null
		echo \" Done! [\$(date)]\"
	fi
	tar -vzxf letsencrypt.tgz
	sudo mv -v letsencrypt /etc
	sudo chown -R root:root /etc/letsencrypt
	command -v restorecon >/dev/null && sudo restorecon -v -R /etc/letsencrypt || echo
"

[ $? = 0 ] && echo "Success!" || (echo "Failed!" && exit 1)

