#!/usr/bin/env bash

# Create superuser on remote Django app server

[[ $# != 4 ]] && echo "Usage: $0 DEST DOMAIN USERNAME PASSWORD" && exit 1

dest=$1 ; shift
domain=$1 ; shift
username=$1 ; shift
password=$1 ; shift


# Create superuser
ssh $dest "/var/www/$domain/manage-prod createsuperuser --noinput --username $username --email=\"$username@$domain.com\""


# Set superuser password
$(dirname $0)/ssh-command $dest $domain "
from django.contrib.auth.models import User;
user = User.objects.get(username=\"$username\");
user.set_password(\"$password\")
user.save(update_fields=[\"password\"])
"
